"""
The AgentState is the shared "memory" that gets passed between every
node (agent) in the graph. Each agent reads what it needs from it and
writes its output back in, so the next agent can pick it up.
"""
from typing import TypedDict, Optional, List, Dict, Any


class AgentState(TypedDict):
    question: str                      # the user's plain-English question
    sql_query: Optional[str]           # SQL generated by Agent 1
    query_result: Optional[List[Dict[str, Any]]]  # rows returned by Agent 2
    error: Optional[str]               # set if SQL execution failed
    retry_count: int                   # how many times we've retried
    chart_json: Optional[str]          # Plotly figure, serialized as JSON
    summary: Optional[str]             # plain-English answer, written last

    # Carried across a retry so that once a fix succeeds, execute_sql can
    # log (failed_sql, error, fixed_sql) to the meta-error memory — these
    # survive generate_sql clearing `error`, unlike `error` itself.
    last_failed_sql: Optional[str]
    last_failed_error: Optional[str]
